### ISSUE TITLE
userBatches Flag

### ISSUE THREAD

**Issue by VanillaSpoon** [codeready-toolchain/toolchain-e2e#762]
Hey, I'm following along the dev sandbox setup.

This command: 
```go run setup/main.go --users 1 --default 1 --custom 0 --username setup -b 1```

Is no longer functional as the userBatches flag (-b) has been removed here: https://github.com/codeready-toolchain/toolchain-e2e/pull/756
 
Just wondering if there is an alternative flag which should be added, or if it can simply be ommited?

https://github.com/codeready-toolchain/toolchain-e2e/blob/135d921fef37a0be084644a6953c02a1a29600b8/setup/README.adoc?plain=1#L90C74-L90C74

**Comment by alexeykazakov** [comment]
@rajivnathan could you please help with this.

**Comment by rajivnathan** [comment]
Sorry, I missed this notification until now. https://github.com/codeready-toolchain/toolchain-e2e/pull/756 introduced a bunch of changes which included removal of the -b flag but looks like I missed removing it in the README in a couple of places. My apologies. Will update the README but yes you can omit it.

**Comment by rajivnathan** [comment]
https://github.com/codeready-toolchain/toolchain-e2e/pull/763 fixes the README. @VanillaSpoon thanks for raising this
